### PR TITLE
Add support for tags

### PR DESCRIPTION
**Pull request by quanganhdo**
My attempt to implement support for tags (https://github.com/tobimori/streamdeck-toggl/issues/3).

### CODE REVIEW

**Comment by tobimori** [comment]
Sorry for taking so long. I'll merge this soon.

**Comment by mg0716** [comment]
@tobimori Yo! Would love to see this support come in, and it's been about a month since your last update here. Any chance we could get a merge soon?

Thanks!

**Comment by Bantor** [comment]
Hi @tobimori. What does it look like? Will the merge still be completed?

**Comment by tobimori** [comment]
Hi! Sorry for taking so long. I appreciate your efforts. I've been pretty busy the past months and didn't have access to my Stream Deck for a long time. 

I'm currently working on a rewrite and it will include this feature. Although I can't make any promises, I'm expecting it to be finished in 1 or 2 weeks.

**Pull request closed without merging**
