### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by angry-bender**
Added API Depreciation instructions as per #41

### CODE REVIEW

**Comment by tobimori** [comment]
Can you add instructions for macOS as well?

**Comment by tobimori** [comment]
the best way would be if someone could follow this guide and package a release for me to upload: https://docs.elgato.com/sdk/plugins/packaging

**Comment by angry-bender** [comment]
> Can you add instructions for macOS as well?

I dont have a MacOS device to test on unfortunatley, but let me see what i can dig up



> the best way would be if someone could follow this guide and package a release for me to upload: https://docs.elgato.com/sdk/plugins/packaging

Happy to take a crack at this one

**Comment by matejcerny** [comment]
The path on macos is `~/Library/Application\ Support/com.elgato.StreamDeck/Plugins/io.moeritz.streamdeck.toggl.sdPlugin`

**Comment by angry-bender** [comment]
Thank you, just working on packaging that one at the moment, once i get the newly required previews directory from the style guide

**Comment by tobimori** [comment]
Maybe you want to use the banner from the rewrite branch which is up to date with the new branding of Toggl: https://github.com/tobimori/streamdeck-toggl/blob/rewrite/resources/GitHubBanner.png

**Comment by angry-bender** [comment]
I've uploaded the packaged release in the zip file below :-)

[io.moeritz.streamdeck.toggl.streamDeckPlugin.zip](https://github.com/tobimori/streamdeck-toggl/files/15162736/io.moeritz.streamdeck.toggl.streamDeckPlugin.zip)

**Comment by angry-bender** [comment]
Looks like that package might be able to be uploaded to update the store too

```Publish to the Store

Submit your plugins by sending an email to [maker@elgato.com](mailto:maker@elgato.com?subject=New%20Plugin:%20&body=Hello%20Elgato%20Team,%0D%0A%0D%0AUser:%0D%0A%0D%0ARelease%20Notes:%0D%0A%0D%0ASupport%20Link:%0D%0A%0D%0ACategory:) with the following:

    Download: A link to download the plugin.

    User: A unique username or an email address.

    Release Notes: What changed with the new version of your plugin? (features/bug fixes)

    Support: Where can users contact you if they have problems? (email, contact form, etc.)

    Category: Under which category do you want to have your plugin listed in the store (only one category is allowed at the moment).

We are working on a developer portal to streamline this experience
```

https://docs.elgato.com/sdk/plugins/distribution

**Pull request merged**
